/* Mendix Context */
export const LOAD_CONTEXT_SUCCESS = 'LOAD_CONTEXT_SUCCESS';

/* Courses */
export const CREATE_COURSES_SUCCESS = 'CREATE_COURSES_SUCCESS';
export const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';

/* Authors */
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
